repos:
  # Standard hooks
  #
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: \.(md|csv)$

#  # Autoformat: Bash scripts
#  - repo: https://github.com/lovesegfault/beautysh
#    rev: v6.2.1
#    hooks:
#      - id: beautysh
#
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      # This requires shellcheck to be installed manually so is disabled by default
      - id: shellcheck
        stages:
          - manual

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

# pre-commit.ci config reference: https://pre-commit.ci/#configuration
ci:
  autoupdate_schedule: monthly
